[package]
name = "catastrophic_integration_tests"
version.workspace = true
edition.workspace = true

[dev-dependencies]
bintest.workspace = true
once_cell.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }
